[package]
name = "osm-io"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3"
prost = "0.11"
reqwest = { version = "0.11", features = ["blocking", "json"] }
log = "0.4"
simple_logger = "4.0"
flate2 = "1.0"
thiserror = "1.0"
rayon = "1.6"
chrono = "0.4"
json = "0.12"
transient-btree-index = "0.5"
regex = "1.7"
postgres = "0.19"
num-format = "0.4"
num_cpus = "1.15"
command-executor = { path = "../command-executor" }
fsds = { path = "../fsds" }
rand = "0.8.5"
data-encoding = "2.3.3"


[build-dependencies]
prost-build = "0.11"
