[package]
name = "osm-io"
authors = ["Giora Kosoi"]
license = "MIT OR Apache-2.0"
description = "Read and write OSM data"
homepage = "https://www.navigatorsguild.io/"
repository = "https://github.com/navigatorsguild/osm-io"
readme = "README.md"
keywords = ["OSM", "open", "street", "map", "geo"]
categories = ["science::geo"]
edition = "2021"
version = "0.1.0"

[dependencies]
rand = "0.8.5"
anyhow = "1.0.70"
escape_string = "0.1.2"
command-executor = "0.1.0"
text-file-sort = "0.1.0"
unescape = "0.1.0"
uuid = { version = "1.4.1", features = ["v4", "std"] }
num-format = "0.4.4"
bytes = "1.4.0"
prost = "0.11.9"
log = "0.4.19"
simple_logger = "4.2.0"
flate2 = "1.0.26"
chrono = "0.4.26"
json = "0.12.4"
transient-btree-index = "0.5.0"
regex = "1.9.1"
postgres = "0.19.5"
num_cpus = "1.16.0"
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
tempfile = "3.6.0"

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
benchmark-rs = "0.1.0"
