[package]
name = "osm-io"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.3"
prost = "0.11"
reqwest = { version = "0.11", features = ["blocking", "json"] }
log = "0.4"
simple_logger = "4.0"
flate2 = "1.0"
thiserror = "1.0"
rayon = "1.6"
chrono = "0.4"
json = "0.12"
command-executor = { path = "../command-executor" }


[build-dependencies]
prost-build = "0.11"
