[package]
name = "osm-io"
authors = ["Giora Kosoi"]
license = "MIT OR Apache-2.0"
description = "Read and write OSM data"
homepage = "https://www.navigatorsguild.io/"
repository = "https://github.com/navigatorsguild/osm-io"
readme = "README.md"
keywords = ["OSM", "open", "street", "map", "geo"]
categories = ["science::geo"]
edition = "2021"
version = "0.0.7-alpha"

[dependencies]
bytes = "1.3"
prost = "0.11"
log = "0.4"
simple_logger = "4.0"
flate2 = "1.0"
chrono = "0.4"
json = "0.12"
transient-btree-index = "0.5"
regex = "1.7"
postgres = "0.19"
num-format = "0.4"
num_cpus = "1.15"
rand = "0.8.5"
data-encoding = "2.3.3"
anyhow = "1.0.70"
escape_string = "0.1.2"
command-executor = "0.1.0"
text-file-sort = "0.0.2-alpha"
unescape = "0.1.0"

[build-dependencies]
prost-build = "0.11"

[dev-dependencies]
benchmark-rs = "0.0.10-alpha"
